### PR TITLE
Refactor rules based on new Tinkerbell labels, add lint-install repo

### PR DESCRIPTION
**Pull request by tstromberg**
A fairly large refactoring of the rules, primarily around the new `kind/` and `priority/` labels that have been deployed within the Tinkerbell repos.

### CODE REVIEW

**Comment by displague** [comment]
This is deployed on the usual DNS name and port as a preview ahead of the merge. Let me know if this is what you expected to see.

Looks good to me.

**Comment by tstromberg** [comment]
Thank you - it looks good. I tested this locally as well (I should probably contribute instructions for doing so!)

**Comment by tstromberg** [comment]
I made a small change to keep the current page ID's to avoid breaking links.

I also think we can still use some daily triage, so I kept the old name there.

**Comment by displague** [comment]
deployed with the latest changes

**Pull request merged**
